// Each new term in the Fibonacci sequence is generated by adding
// the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed
// four million, find the sum of the even-valued terms.

const EULER_2_MAX_FIBONACCI = 4000000;

export default function euler2() {
  let prevFibonacci = 0;
  let fibonacci = 1;
  let resultSumm = 0;

  do {
    const resultFibonacci = fibonacci + prevFibonacci;
    prevFibonacci = fibonacci;
    fibonacci = resultFibonacci;

    resultSumm =
      resultFibonacci % 2 === 0 ? resultSumm + resultFibonacci : resultSumm;
  } while (fibonacci < EULER_2_MAX_FIBONACCI);

  return resultSumm;
}

// console.time();
// console.log(euler2());
// console.timeEnd();
